#!/usr/bin/env python3
"""Frozen real-input cases; the boot projection explicitly defers two pragmas."""
import pathlib
from expand_cases import quoted

ROOT = pathlib.Path(__file__).resolve().parents[1]


def corpus():
    base = ROOT / 'reference/cakeml/candle/prover'
    records = (base / 'candle_records.ml').read_text()
    boot = (base / 'candle_boot.ml').read_text()
    # Exact snapshot fragments, deliberately not a new/general preprocessor.
    pragmas = [
        '(*CML\nval negint = Int.~;\nval negfloat = Double.~;\n*)',
        "(*CML\n(* OCaml parser doesn't like the tilde *)\nval rat_minus = Rat.~;\n*)",
    ]
    for block in pragmas:
        if boot.count(block) != 1:
            raise ValueError('boot snapshot changed: audit the pragma projection')
        boot = boot.replace(block, ''.join('\n' if c == '\n' else ' ' for c in block))
    if '(*CML' in boot:
        raise ValueError('unaccounted boot pragma')
    return [('records/raw', records), ('boot/Candle-only-projection', boot)]


if __name__ == '__main__':
    print('(* Generated by corpus_inputs.py from the frozen copied corpus. *)')
    print('val corpus_cases = [')
    print(',\n'.join('(' + quoted(n) + ',' + quoted(s) + ')' for n, s in corpus()))
    print('];')
