#!/usr/bin/env python3
"""Extract one constructor-valued fixture from a completed HOL oracle log.

Writes CakeML source to stdout, never invokes the candidate parser. The required
count guards against accidentally accepting a partial oracle run.
"""

import argparse
import pathlib
import sys


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("log", type=pathlib.Path)
    parser.add_argument("--kind", required=True, choices=(
        "lex", "tree", "parse", "name", "path", "type", "literal", "pattern",
        "record", "ctor", "typedefs", "exception", "unit", "cakelex", "cakegrammar", "limits",
        "cakeconversion", "cakehelper", "recordprep", "expr", "decl", "inherited", "expanded", "corpus", "candlehelper"))
    parser.add_argument("--count", type=int, required=True)
    args = parser.parse_args()
    prefix = args.kind.upper() + "_GOLDEN "
    entries = [line.strip()[len(prefix):] for line in args.log.read_text().splitlines()
               if line.strip().startswith(prefix)]
    if len(entries) != args.count or not entries:
        parser.error(f"expected {args.count} {args.kind} cases, got {len(entries)}")
    if any(not entry.endswith(",") for entry in entries):
        parser.error("incomplete fixture line")
    binding = "lexer" if args.kind == "lex" else "parser" if args.kind == "parse" else args.kind
    print("(* Generated by the independent HOL oracle; see tests/README.md for provenance. *)")
    result_types = {
        "name": "string", "path": "string list", "type": "Ast.ast_t",
        "literal": "Ast.lit",
        "expr": "Ast.exp",
        "decl": "Ast.dec list",
        "pattern": "(((string,string) Ast.id * string list),Ast.pat) sum list",
        "record": "(string * Ast.ast_t) list",
        "ctor": "CandleTypeDeclarations.ctor",
        "typedefs": "CandleTypeDeclarations.type_def list",
        "exception": "Ast.dec", "unit": "unit",
    }
    annotation = (" : (CandleGrammar.nonterm * string * string * "
                  f"((Ast.locs * string),{result_types[args.kind]}) sum) list"
                  if args.kind in result_types else "")
    if args.kind == "cakegrammar":
        annotation = (" : (CakeGrammar.nonterm * string * "
                      "((CakeTokens.token * Ast.locs) list,"
                      "CakeGrammar.ptree list,string) CandlePeg.result) list")
    if args.kind == "cakeconversion":
        annotation = (" : (CakeGrammar.nonterm * string * string * "
                      "CakeConversionTests.value option) list")
    if args.kind in ("cakehelper", "recordprep", "inherited", "candlehelper"):
        annotation = " : (string * (unit -> bool)) list"
    print(f"val {binding}_golden{annotation} = [")
    print("\n".join(entries[:-1] + [entries[-1][:-1]]))
    print("];")
    return 0


if __name__ == "__main__":
    sys.exit(main())
