#!/usr/bin/env python3
"""Compatibility characterization and pinned local corpus inputs; no candidate."""
import hashlib
import json
import pathlib

from expand_cases import quoted

ROOT = pathlib.Path(__file__).resolve().parents[1]


def cases():
    # The first two forms come from cake-jurban commit 51513f0dfb3bcf169c8342de6efd04e5b7b4e00b.
    # These characterize the locally documented limitation, not verified verbatim
    # reproductions of GitHub #1019 (its issue body is not in the local notes).
    expressions = [
        ('conditional/add-bare', 'a + if p then b else c'),
        ('conditional/tuple-bare', '(a, if p then b else c)'),
        ('conditional/add-parenthesized', 'a + (if p then b else c)'),
        ('conditional/tuple-parenthesized', '(a, (if p then b else c))'),
        ('conditional/first-component', '(if p then a else b, c)'),
        ('conditional/first-parenthesized', '((if p then a else b), c)'),
        ('conditional/tuple-branches', 'if p then a,b else c,d'),
        ('conditional/tuple-branches-parenthesized', 'if p then (a,b) else (c,d)'),
        ('conditional/cat-bare', 'a ^ if p then b else c'),
        ('conditional/cat-parenthesized', 'a ^ (if p then b else c)'),
        ('precedence/cat-compare', '"a" ^ "b" = "ab"'),
        ('precedence/append-compare', '[a] @ [b] = [a;b]'),
        ('conditional/dangling-else', 'if p then if q then a else b else c'),
        ('conditional/missing-else-body', '(a, (if p then b else))'),
    ]
    result = [(name, 'let result = ' + source + ';;') for name, source in expressions]
    base = ROOT / 'tests/corpus'
    for entry in json.loads((base / 'manifest.json').read_text()):
        data = (base / entry['name']).read_bytes()
        if hashlib.sha256(data).hexdigest() != entry['sha256']:
            raise ValueError('corpus snapshot hash mismatch: ' + entry['name'])
        result.append(('corpus/' + entry['name'], data.decode()))
    return result


if __name__ == '__main__':
    print('(* Generated by limits_inputs.py; exact sources and provenance are retained. *)')
    print('val limits_cases = [')
    print(',\n'.join('(' + quoted(n) + ',' + quoted(s) + ')' for n, s in cases()))
    print('];')
